# Generated by Django 5.2 on 2025-04-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('shipment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('supplier_prediction', models.CharField(max_length=255)),
                ('account_prediction', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeocodedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'unique_together': {('city', 'country')},
            },
        ),
    ]
