# Generated by Django 5.2 on 2025-04-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geocodedlocation',
            unique_together={('postal_code', 'country')},
        ),
        migrations.AddField(
            model_name='geocodedlocation',
            name='postal_code',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='geocodedlocation',
            name='city',
        ),
    ]
