# Generated by Django 5.2 on 2025-04-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_alter_geocodedlocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocodedlocation',
            name='postal_code',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
